import { Incident, Metrics, User } from "@/types/types";

export const user: User = {
  id: 'user-001',
  email: 'nuno.almeida@company.com',
  name: 'Nuno Almeida',
  role: 'SOC Analyst L2',
  created_at: new Date('2023-01-15T09:30:00Z').toISOString(),
};

export const metrics: Metrics = {
  cgScore: 78,
  cgTrend: 'up',
  incidentsBySevertiy: { low: 12, medium: 8, high: 3 },
  automationRate: 73,
  monitoredAssets: 1247,
  mttr: 45,
  mttrTrend: -12,
  totalInvestigated: 156,
  totalEscalated: 23,
  truePositives: 134,
};

export const incidents: Incident[] = [
  {
    id: '1',
    title: 'Suspicious Network Traffic Detected',
    severity: 'high',
    status: 'investigating',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: 'John Doe',
    description: 'Unusual outbound traffic detected from internal subnet 192.168.1.0/24 to external IP addresses.',
    source_ip: '192.168.1.45',
    affected_assets: ['WS-001', 'SRV-DB-01'],
    response_time: 12,
  },
  {
    id: '2',
    title: 'Failed Login Attempts',
    severity: 'medium',
    status: 'open',
    created_at: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: null,
    description: 'Multiple failed login attempts detected for admin account from external IP.',
    source_ip: '203.0.113.15',
    affected_assets: ['AD-001'],
    response_time: null,
  },
  {
    id: '3',
    title: 'Malware Detection Alert',
    severity: 'high',
    status: 'open',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: 'Jane Smith',
    description: 'Potential malware detected on workstation. File quarantined automatically.',
    source_ip: null,
    affected_assets: ['WS-045'],
    response_time: null,
  },
  {
    id: '4',
    title: 'Unauthorized Access Attempt',
    severity: 'medium',
    status: 'resolved',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: 'Mike Johnson',
    description: 'Attempted access to restricted file shares from unauthorized user account.',
    source_ip: '10.0.0.25',
    affected_assets: ['FS-001'],
    response_time: 28,
  },
  {
    id: '5',
    title: 'DDoS Attack Detected',
    severity: 'high',
    status: 'investigating',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: 'Sarah Connor',
    description: 'Large volume of requests detected targeting web application server.',
    source_ip: 'Multiple',
    affected_assets: ['WEB-001', 'LB-001'],
    response_time: 8,
  },
  {
    id: '6',
    title: 'Phishing Email Detected',
    severity: 'low',
    status: 'resolved',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    assigned_to: null,
    description: 'Automated email filter detected and blocked potential phishing attempt.',
    source_ip: null,
    affected_assets: [],
    response_time: 2,
  },
]